package com.real.proj.amc.model.quote;

public enum QStates {
  INITIAL, NEW_QUOTATION_CREATED, USER_DATA_PROVIDED, QUOTATION_GENERATED, USER_NOTIFIED, USER_ACCEPTED, QUOTATION_REGENERATED, QUOTATION_APPROVED, PAYMENT_MADE, SUBSCRIBED;
}
