package com.real.proj.amc.model.quote;

public enum QStates {
  INITIAL,
  NEW_QUOTATION_CREATED,
  USER_DATA_PROVIDED,
  QUOTATION_GENERATED,
  USER_NOTIFIED,
  USER_ACCEPTED,
  QUOTATION_REGENERATED,
  QUOTATION_APPROVED,
  PAYMENT_PENDING,
  PAYMENT_MADE,
  SUBSCRIBED,
  QUOTATION_EXPIRED,
  SUBSCRIPTION_EXPIRED,
  PAYMENT_INITIATED,
  USER_REJECTED,
  QUOTATION_REJECTED;
}
